### ISSUE TITLE
Increment by whole integers only

### ISSUE THREAD

**Issue by LeftRightOut** [princejwesley/circular-slider#12]
Is it possible to allow to increment by values less than 1? As in 0.5 for each step?

**Comment by senthilporunan** [comment]
Hi,

Now, we are supporting increment value by 1. We will make necessary code changes to make this one as configurable one.

Thanks,
Senthil.

**Comment by senthilporunan** [comment]
We don't need any code changes for your requirement. You can use formLabel, that will help you to support. Please refer this fiddle : http://jsfiddle.net/senthilporunan/Lat9zps7/34/

Let us know if you are facing any more issues.
