### ISSUE TITLE
setRadius(value)

### ISSUE THREAD

**Issue by DamonDeep** [princejwesley/circular-slider#7]
It's possible set radius dynamically?
ex.
var circularSlider = $('#slider').CircularSlider({ 
    min : 0, 
    max: 359, 
    value : 10,
    radius : 120;
});

I want to do 

circularSlider.setRadius(200); 

to change the radius of the active  circularSlider

**Comment by senthilporunan** [comment]
Here after, You can call setRadius and getRadius api dynamically. 

Added through pull request: https://github.com/princejwesley/circular-slider/pull/8
